In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\ELGRM\\OneDrive\\Desktop\\premier league predictor\\data\\raw\\raw_data.csv", dtype={"Season_code": str})

C:\Users\ELGRM\AppData\Local\Temp\ipykernel_25668\1533727240.py:1: DtypeWarning: Columns (100) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:\\Users\\ELGRM\\OneDrive\\Desktop\\premier league predictor\\data\\raw\\raw_data.csv", dtype={"Season_code": str})

In [4]:
df

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,PPA,SKBH,SKBD,SKBA,PPCH,PPCD,PPCA,SKBCH,SKBCD,SKBCA
0,E0,19/08/00,Charlton,Man City,4.0,0.0,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,19/08/00,Chelsea,West Ham,4.0,2.0,H,1.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,19/08/00,Coventry,Middlesbrough,1.0,3.0,A,1.0,1.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,19/08/00,Derby,Southampton,2.0,2.0,D,1.0,2.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,19/08/00,Leeds,Everton,2.0,0.0,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9136,E0,30/08/2026,Chelsea,Brighton,4.0,3.0,H,3.0,1.0,H,...,4.0,1.80,3.80,4.0,1.83,3.75,3.80,1.83,3.8,3.80
9137,E0,30/08/2026,Leeds,Brentford,1.0,1.0,D,0.0,1.0,A,...,2.7,2.60,3.25,2.7,2.75,3.30,2.50,2.75,3.4,2.45
9138,E0,30/08/2026,Sunderland,Fulham,1.0,0.0,H,0.0,0.0,D,...,3.0,2.40,3.10,2.9,2.20,3.25,3.30,2.20,3.3,3.30
9139,E0,30/08/2026,Man United,Ipswich,5.0,2.0,H,1.0,1.0,D,...,7.0,1.40,4.75,7.0,1.33,5.00,8.00,1.33,5.5,8.00
9140,E0,31/08/2026,Aston Villa,Arsenal,0.0,1.0,A,0.0,0.0,D,...,1.5,6.25,4.00,1.5,6.50,4.50,1.44,6.50,4.5,1.44

In [5]:
df["HomeTeam"]

0          Charlton
1           Chelsea
2          Coventry
3             Derby
4             Leeds
           ...
9136        Chelsea
9137          Leeds
9138     Sunderland
9139     Man United
9140    Aston Villa
Name: HomeTeam, Length: 9141, dtype: object

In [6]:
name_new ={
    "Man Utd": "Manchester United",
    "Man City": "Manchester City",
    "Man United": "Manchester United",
    "Tottenham": "Tottenham Hotspur",
}
df["HomeTeam"] = df["HomeTeam"].replace(name_new)
df["AwayTeam"] = df["AwayTeam"].replace(name_new)

In [7]:
df  = df.drop_duplicates()

In [8]:
df = df.dropna(subset=["HomeTeam", "AwayTeam" , "Date" ,"FTR"])

In [9]:
df

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,PPA,SKBH,SKBD,SKBA,PPCH,PPCD,PPCA,SKBCH,SKBCD,SKBCA
0,E0,19/08/00,Charlton,Manchester City,4.0,0.0,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,19/08/00,Chelsea,West Ham,4.0,2.0,H,1.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,19/08/00,Coventry,Middlesbrough,1.0,3.0,A,1.0,1.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,19/08/00,Derby,Southampton,2.0,2.0,D,1.0,2.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,19/08/00,Leeds,Everton,2.0,0.0,H,2.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9136,E0,30/08/2026,Chelsea,Brighton,4.0,3.0,H,3.0,1.0,H,...,4.0,1.80,3.80,4.0,1.83,3.75,3.80,1.83,3.8,3.80
9137,E0,30/08/2026,Leeds,Brentford,1.0,1.0,D,0.0,1.0,A,...,2.7,2.60,3.25,2.7,2.75,3.30,2.50,2.75,3.4,2.45
9138,E0,30/08/2026,Sunderland,Fulham,1.0,0.0,H,0.0,0.0,D,...,3.0,2.40,3.10,2.9,2.20,3.25,3.30,2.20,3.3,3.30
9139,E0,30/08/2026,Manchester United,Ipswich,5.0,2.0,H,1.0,1.0,D,...,7.0,1.40,4.75,7.0,1.33,5.00,8.00,1.33,5.5,8.00
9140,E0,31/08/2026,Aston Villa,Arsenal,0.0,1.0,A,0.0,0.0,D,...,1.5,6.25,4.00,1.5,6.50,4.50,1.44,6.50,4.5,1.44

In [10]:
df.columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR',
       ...
       'PPA', 'SKBH', 'SKBD', 'SKBA', 'PPCH', 'PPCD', 'PPCA', 'SKBCH', 'SKBCD',
       'SKBCA'],
      dtype='object', length=227)

In [11]:
core_cols = [
    # Match info
    "Season_code", "Date", "HomeTeam", "AwayTeam",
    # Full-time & Half-time Targets
    "FTHG", "FTAG", "FTR", "HTHG", "HTAG", "HTR",
    # Match stats (for form & feature calculation)
    "HS", "AS", "HST", "AST", "HC", "AC", "HF", "AF", "HY", "AY", "HR", "AR", "Referee",
    # Benchmark Odds (Bet365 & Market Average)
    "B365H", "B365D", "B365A"
]

# Keep only the columns that exist in the raw dataframe
df_clean = df[[col for col in core_cols if col in df.columns]].copy()

In [12]:
df_clean

,Season_code,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HF,AF,HY,AY,HR,AR,Referee,B365H,B365D,B365A
0,0001,19/08/00,Charlton,Manchester City,4.0,0.0,H,2.0,0.0,H,...,13.0,12.0,1.0,2.0,0.0,0.0,Rob Harris,NaN,NaN,NaN
1,0001,19/08/00,Chelsea,West Ham,4.0,2.0,H,1.0,0.0,H,...,19.0,14.0,1.0,2.0,0.0,0.0,Graham Barber,NaN,NaN,NaN
2,0001,19/08/00,Coventry,Middlesbrough,1.0,3.0,A,1.0,1.0,D,...,15.0,21.0,5.0,3.0,1.0,0.0,Barry Knight,NaN,NaN,NaN
3,0001,19/08/00,Derby,Southampton,2.0,2.0,D,1.0,2.0,A,...,11.0,13.0,1.0,1.0,0.0,0.0,Andy D'Urso,NaN,NaN,NaN
4,0001,19/08/00,Leeds,Everton,2.0,0.0,H,2.0,0.0,H,...,21.0,20.0,1.0,3.0,0.0,0.0,Dermot Gallagher,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9136,2627,30/08/2026,Chelsea,Brighton,4.0,3.0,H,3.0,1.0,H,...,6.0,12.0,1.0,3.0,0.0,0.0,M Oliver,1.83,4.0,4.00
9137,2627,30/08/2026,Leeds,Brentford,1.0,1.0,D,0.0,1.0,A,...,5.0,13.0,0.0,4.0,0.0,0.0,T Harrington,2.60,3.3,2.70
9138,2627,30/08/2026,Sunderland,Fulham,1.0,0.0,H,0.0,0.0,D,...,10.0,15.0,0.0,2.0,0.0,0.0,M Salisbury,2.40,3.2,3.10
9139,2627,30/08/2026,Manchester United,Ipswich,5.0,2.0,H,1.0,1.0,D,...,7.0,12.0,1.0,3.0,0.0,0.0,C Pawson,1.42,5.0,7.00
9140,2627,31/08/2026,Aston Villa,Arsenal,0.0,1.0,A,0.0,0.0,D,...,17.0,6.0,3.0,1.0,0.0,0.0,J Gillett,6.00,4.1,1.53

In [13]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9140 entries, 0 to 9140
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Season_code  9140 non-null   object
 1   Date         9140 non-null   object
 2   HomeTeam     9140 non-null   object
 3   AwayTeam     9140 non-null   object
 4   FTHG         9140 non-null   float64
 5   FTAG         9140 non-null   float64
 6   FTR          9140 non-null   object
 7   HTHG         9140 non-null   float64
 8   HTAG         9140 non-null   float64
 9   HTR          9140 non-null   object
 10  HS           9140 non-null   float64
 11  AS           9140 non-null   float64
 12  HST          9140 non-null   float64
 13  AST          9140 non-null   float64
 14  HC           9140 non-null   float64
 15  AC           9140 non-null   float64
 16  HF           9140 non-null   float64
 17  AF           9140 non-null   float64
 18  HY           9140 non-null   float64
 19  AY           9140 non-null   float64
 20  HR           9140 non-null   float64
 21  AR           9140 non-null   float64
 22  Referee      9140 non-null   object
 23  B365H        8380 non-null   float64
 24  B365D        8380 non-null   float64
 25  B365A        8380 non-null   float64
dtypes: float64(19), object(7)
memory usage: 1.9+ MB

In [14]:
df_clean["Date"] = pd.to_datetime(df_clean["Date"], dayfirst=True, errors="coerce")

C:\Users\ELGRM\AppData\Local\Temp\ipykernel_25668\605525522.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_clean["Date"] = pd.to_datetime(df_clean["Date"], dayfirst=True, errors="coerce")

In [15]:
df_clean = df_clean.sort_values("Date").reset_index(drop=True)

In [16]:
df_clean

,Season_code,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HF,AF,HY,AY,HR,AR,Referee,B365H,B365D,B365A
0,0001,2000-08-19,Charlton,Manchester City,4.0,0.0,H,2.0,0.0,H,...,13.0,12.0,1.0,2.0,0.0,0.0,Rob Harris,NaN,NaN,NaN
1,0001,2000-08-19,Chelsea,West Ham,4.0,2.0,H,1.0,0.0,H,...,19.0,14.0,1.0,2.0,0.0,0.0,Graham Barber,NaN,NaN,NaN
2,0001,2000-08-19,Coventry,Middlesbrough,1.0,3.0,A,1.0,1.0,D,...,15.0,21.0,5.0,3.0,1.0,0.0,Barry Knight,NaN,NaN,NaN
3,0001,2000-08-19,Derby,Southampton,2.0,2.0,D,1.0,2.0,A,...,11.0,13.0,1.0,1.0,0.0,0.0,Andy D'Urso,NaN,NaN,NaN
4,0001,2000-08-19,Leeds,Everton,2.0,0.0,H,2.0,0.0,H,...,21.0,20.0,1.0,3.0,0.0,0.0,Dermot Gallagher,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9135,2627,2026-08-30,Sunderland,Fulham,1.0,0.0,H,0.0,0.0,D,...,10.0,15.0,0.0,2.0,0.0,0.0,M Salisbury,2.40,3.2,3.10
9136,2627,2026-08-30,Manchester United,Ipswich,5.0,2.0,H,1.0,1.0,D,...,7.0,12.0,1.0,3.0,0.0,0.0,C Pawson,1.42,5.0,7.00
9137,2627,2026-08-30,Chelsea,Brighton,4.0,3.0,H,3.0,1.0,H,...,6.0,12.0,1.0,3.0,0.0,0.0,M Oliver,1.83,4.0,4.00
9138,2627,2026-08-30,Leeds,Brentford,1.0,1.0,D,0.0,1.0,A,...,5.0,13.0,0.0,4.0,0.0,0.0,T Harrington,2.60,3.3,2.70
9139,2627,2026-08-31,Aston Villa,Arsenal,0.0,1.0,A,0.0,0.0,D,...,17.0,6.0,3.0,1.0,0.0,0.0,J Gillett,6.00,4.1,1.53

In [17]:

from pathlib import Path


Path("data/processed").mkdir(parents=True, exist_ok=True)
df_clean.to_csv("data/processed/matches_clean.csv", index=False)

In [18]:
df_clean.columns

Index(['Season_code', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HC', 'AC', 'HF', 'AF',
       'HY', 'AY', 'HR', 'AR', 'Referee', 'B365H', 'B365D', 'B365A'],
      dtype='object')